name: Hide bot comments

on:
  workflow_dispatch:
    inputs:
      author:
        description: 'Comment author'
        required: true
        default: 'github-actions'
        type: choice
        options:
          - github-actions
          - github-actions[bot]
          - seqan-actions
      issue_number:
        description: 'The issue number'
        required: true
        type: string
      leave_visible:
        description: 'The number of most recent comments to leave untouched'
        required: false
        default: '0'

jobs:
  hide-comments-action:
    runs-on: ubuntu-latest
    steps:
    - name: Hide comments
      uses: kanga333/comment-hider@v0.4.0
      with:
        github_token: ${{ secrets.SEQAN_ACTIONS_PAT }}
        hide_user_name: ${{ github.event.inputs.author }}
        issue_number: ${{ github.event.inputs.issue_number }}
        leave_visible: ${{ github.event.inputs.leave_visible }}
